#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#    Jul 02, 2019 06:04:09 PM EEST  platform: Windows NT

import sys
import engine

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True


def set_Tk_var():
    global tag
    tag = tk.StringVar()


def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top
    root.resizable(False, False)
    w.InputField.bind('<Return>', engine.saveToTxtFile)
    w.InputField.focus()

    # Run Functions From Engine.
    w.Confirm.configure(command=engine.saveToTxtFile)


def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None


if __name__ == '__main__':
    import MainWindow
    MainWindow.vp_start_gui()
